name: Run YCQL Example
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Load Schema of YCQL
        run: |
          docker run --name yb -d -p2021:7000 -p2010:9000 -p2023:5433 -p2011:9042 yugabytedb/yugabyte:latest bin/yugabyted start --daemon=false
          docker ps;
          docker exec -i yb /home/yugabyte/bin/ycqlsh < .github/setups/keyspace.ycql;