name: Run YCQL Example
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Load Schema of YCQL
        run: |
          docker run -d --name yb -p 2011:9042 -d yugabytedb/yugabyte;
          docker ps;
          docker exec -i yb ycqlsh < .github/setups/keyspace.ycql;