name: Run YCQL Example
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Setup YugabyteDB cluster
        uses: yugabyte/yugabyte-db-action@master
        with:
          yb_image_tag: 2.2.0.0-b80
          yb_master_ui_port: 7000
          yb_tserver_ui_port: 9000
          ysql_port: 5433
          ycql_port: 9042
      - name: Load Schema of YCQL
        run: |
          docker ps;
          docker exec -i yb /home/yugabyte/bin/ycqlsh < .github/setups/keyspace.ycql;