name: Run YCQL Example
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: set
        uses: yugabyte/yugabyte-db-action@master
        with:
          yb_master_ui_port: 7000
          yb_tserver_ui_port: 9000
          ysql_port: 5433
          ycql_port: 9042

      - name: Load Schema of YCQL
        run: |
          temp=$(sudo docker ps | grep yugabyte | awk '{print $1}')
          docker exec -i $temp /home/yugabyte/bin/ycqlsh < .github/setups/keyspace.ycql;
          docker exec -i $temp ycqlsh -e 'use test;select * from shop';
